### ISSUE TITLE
Deploy portscout with token credentials

### ISSUE THREAD

**Issue by koobs** [freebsd/portscout#13]
- [x] Review & merge #9 (@koobs)
- [x] Tag new release `0.8.1.5` (@grembo )
- [x] Update, review and commit `ports-mgmt/portscout`  (@grembo)
- [x] Re-test if token procedure and portscout + token (#9) still works as it did in 2020 (@grembo) [0]
- [x] [Generate new github token](https://github.com/freebsd/portscout/pull/9#issuecomment-583827140) for a project account (@zi0r)
- [ ] Test #9 locally with new token creds (@zi0r, ongoing)
- ~[ ] Obtain ssh access to portscout environment and su for @grembo and @koobs (@koobs)~
- [x] Deploy (anyone)
- ~[ ] Document access and deployment process in Wiki (@koobs)~

[0] Tested locally with personal account github token (sysutils category, about 1600 ports).

**Comment by grembo** [comment]
@koobs Should we create a follow-up task for `[ ] Obtain ssh access to portscout environment and su for @grembo and @koobs (@koobs)"`

**Comment by koobs** [comment]
> @koobs Should we create a follow-up task for `[ ] Obtain ssh access to portscout environment and su for @grembo and @koobs (@koobs)" / [ ] Document access and deployment process in Wiki (@koobs)`?

Yep, I think so. Im not otherwise sure how to proceed given cluster doesn't manage it. @zi0r can you help?

**Comment by grembo** [comment]
@koobs This was deployed on Feb 7th 2022 (as indicated by the checkbox above). We never closed it though, which is what I'll do now.
